### ISSUE TITLE
Document scope requirement

### ISSUE THREAD

**Issue by mridgway** [johnkernke/passport-twitchtv#1]
Right now this passport doesn't seem to work unless you pass a `scope` option of at least `user_read` to the strategy:

```
passport.use(new TwitchStrategy({
    clientID: <clientID>,
    clientSecret: <clientSecret>,
    callbackURL: <callbackURL,
    scope: 'user_read'
}, function (accessToken, refreshToken, profile, done) {
    ...
}));
```

**Comment by johnkernke** [comment]
Updated the documentation and examples to include that a scope is required.

**Comment by kitce** [comment]
I requested an access token from Twitch without scope, and successfully used it to retrieve the public profile with `https://api.twitch.tv/kraken/users/{username}?oauth_token={access_token}`

Therefore, can I assume it is an issue of `passport-oauth2`?
