### ISSUE TITLE
Trying to retrieve subscriber list

### ISSUE THREAD

**Issue by l0sth** [johnkernke/passport-twitchtv#2]
How do you request something from the twitch api with this ? Everything works with the example you provided, but I tried different ways to retrieve the subscriber list (or anything else that requires the oauth token) but no luck..

Thanks!

**Comment by johnkernke** [comment]
From the main [Passport](https://github.com/jaredhanson/passport) repo "Passport's sole purpose is to authenticate requests". I think you might want to look for another node package such as [twitchy](https://www.npmjs.org/package/twitchy) that could use the access token provided by this passport.
